server:
  port: 8085

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: notification-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,orderEventRecovery
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
