CREATE TABLE outbox_event (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    event_type character varying(50) NOT NULL,
    payload text NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    CONSTRAINT outbox_event_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PUBLISHED'::character varying])::text[])))
);

ALTER TABLE outbox_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME outbox_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY outbox_event
    ADD CONSTRAINT outbox_event_pkey PRIMARY KEY (id);

-- Poller filters on status and orders by id; this covers both in one index.
CREATE INDEX idx_outbox_event_status_id ON outbox_event (status, id);
