CREATE TABLE compensation_task (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    order_id bigint,
    idempotency_key character varying(64) NOT NULL,
    status character varying(30) NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    created_at timestamp(6) with time zone NOT NULL,
    resolved_at timestamp(6) with time zone,
    CONSTRAINT compensation_task_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying, 'NEEDS_MANUAL_CORRECTION'::character varying])::text[])))
);

ALTER TABLE compensation_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME compensation_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY compensation_task
    ADD CONSTRAINT compensation_task_pkey PRIMARY KEY (id);

-- Retry job filters on status and orders by id; this covers both in one index.
CREATE INDEX idx_compensation_task_status_id ON compensation_task (status, id);
