-- Baseline migration, captured verbatim (via pg_dump --schema-only) from the real schema
-- Hibernate's ddl-auto: update actually produced.

CREATE TABLE products (
    id bigint NOT NULL,
    category character varying(60),
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(2000),
    image_url character varying(255),
    name character varying(150) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock_quantity integer NOT NULL,
    updated_at timestamp(6) with time zone
);

ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);
